
export const GET_PRODUCTS_DATA='GET_PRODUCTS_DATA';
export const SET_PRODUCTS_DETAIL='SET_PRODUCTS_DETAIL';
export const GET_SELECTED_PRODUCTS_OPTIONS='GET_SELECTED_PRODUCTS_OPTIONS';
export const SELECT_PRODUCT_OPTION_DETAILS='SELECT_PRODUCT_OPTION_DETAILS';
export const DISPLAY_PURCHASE_VIEW='DISPLAY_PURCHASE_VIEW';















