export const VIEW_ROUTE_SCREENS={
    PROCESSING: 'PROCESSING_VIEW',
    RIGHT_PANEL_VIEW:'RIGHT_PANEL_VIEW'
   
}

export const RIGHT_PANEL_VIEW_SCREENS={
    PRODUCT_CATEGORY_VIEW:'PRODUCT_CATEGORY_VIEW',
   DETAIL_PANEL_VIEW:'DETAIL_PANEL_VIEW'
}
