
export const SET_RIGHT_PANEL_SCREEN_TYPE='SET_RIGHT_PANEL_SCREEN_TYPE';
export const RIGHT_PANEL_VIEW_SCREENS='RIGHT_PANEL_VIEW_SCREENS';
export const SET_SELECTED_PRODUCTS='SET_SELECTED_PRODUCTS';


